# Generated by Django 3.1.4 on 2020-12-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surnname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_signature_amount', models.IntegerField(default=10, verbose_name='Required signature amount for submission')),
                ('resubmission_attempts', models.IntegerField(default=3, verbose_name='Permitted amount of initiative resubmission attempts')),
                ('petition_longevity', models.IntegerField(default=2, verbose_name='Amount of days petition can last')),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('edition', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surnname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Date petition created')),
                ('date_closed', models.DateTimeField(verbose_name='Date petition closed')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_maker_app.initiative')),
            ],
        ),
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_maker_app.petition')),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_maker_app.initiator'),
        ),
    ]
